set local check_function_bodies = off;

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "service_role";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "service_role";

create table "public"."Notifications" (
  "id"         bigint                   generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  constraint "Notifications_pkey" primary key (id)
);

alter table "public"."Notifications"
  enable row level security;

create table "public"."appointments" (
  "id"            uuid                     not null default gen_random_uuid(),
  "patient_id"    uuid                     not null,
  "created_by"    uuid                     not null,
  "description"   text,
  "start_time"    timestamp with time zone not null,
  "end_time"      timestamp with time zone not null,
  "status"        text                     not null default 'scheduled'::text,
  "reminder_sent" boolean                  not null default false,
  "created_at"    timestamp with time zone not null default now(),
  "updated_at"    timestamp with time zone not null default now(),
  constraint "appointments_pkey" primary key (id),
  constraint "appointments_status_check" check ((status = ANY (ARRAY['scheduled'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text]))),
  constraint "check_valid_appointment_time" check ((end_time > start_time))
);

alter table "public"."appointments"
  enable row level security;

create table "public"."conversations" (
  "id"         uuid                     not null default gen_random_uuid(),
  "user_a"     uuid                     not null,
  "user_b"     uuid                     not null,
  "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
  "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
  constraint "check_canonical_user_order" check ((user_a < user_b)),
  constraint "conversations_pkey" primary key (id),
  constraint "unique_user_pair" unique (user_a, user_b)
);

alter table "public"."conversations"
  enable row level security;

create table "public"."messages" (
  "id"                  uuid                     not null default gen_random_uuid(),
  "conversation_id"     uuid                     not null,
  "sender_id"           uuid                     not null,
  "content"             text                     not null,
  "media_url"           text,
  "reply_to_message_id" uuid,
  "read_at"             timestamp with time zone,
  "created_at"          timestamp with time zone not null default timezone('utc'::text, now()),
  "media_type"          text,
  "duration_seconds"    numeric,
  "mentioned_patients"  jsonb                    not null default '[]'::jsonb,
  constraint "messages_media_type_check" check (((media_type IS NULL) OR (media_type = ANY (ARRAY['voice'::text, 'image'::text, 'document'::text, 'video'::text])))),
  constraint "messages_pkey" primary key (id)
);

alter table "public"."messages"
  enable row level security;

create table "public"."notifications" (
  "id"         uuid                     not null default gen_random_uuid(),
  "user_id"    uuid                     not null,
  "type"       text                     not null,
  "message"    text                     not null,
  "read"       boolean                  not null default false,
  "patient_id" uuid,
  "created_at" timestamp with time zone not null default now(),
  constraint "notifications_pkey" primary key (id),
  constraint "notifications_type_check"
    check ((type = ANY (ARRAY['message'::text, 'case_status'::text, 'scan_quality'::text, 'shade'::text, 'scan_body'::text, 'sync'::text, 'export'::text, 'appointment'::text])))
);

alter table "public"."notifications"
  enable row level security;

create table "public"."patient_access" (
  "id"           uuid                     not null default gen_random_uuid(),
  "patient_id"   uuid                     not null,
  "user_id"      uuid                     not null,
  "granted_by"   uuid                     not null,
  "created_at"   timestamp with time zone not null default now(),
  "status"       text                     not null default 'approved'::text,
  "requested_by" uuid,
  "approved_by"  uuid,
  constraint "patient_access_pkey" primary key (id),
  constraint "patient_access_status_check" check ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))),
  constraint "patient_access_unique" unique (patient_id, user_id)
);

alter table "public"."patient_access"
  enable row level security;

create table "public"."patient_audit_logs" (
  "id"         uuid                     not null default gen_random_uuid(),
  "patient_id" uuid,
  "actor_id"   uuid                     not null,
  "action"     text                     not null,
  "details"    jsonb                    not null default '{}'::jsonb,
  "created_at" timestamp with time zone not null default now(),
  constraint "patient_audit_logs_pkey" primary key (id)
);

alter table "public"."patient_audit_logs"
  enable row level security;

create table "public"."patient_notes" (
  "id"              uuid                     not null default gen_random_uuid(),
  "patient_id"      uuid                     not null,
  "author_id"       uuid                     not null,
  "note_ciphertext" text                     not null,
  "created_at"      timestamp with time zone not null default now(),
  "updated_at"      timestamp with time zone not null default now(),
  constraint "patient_notes_pkey" primary key (id)
);

alter table "public"."patient_notes"
  enable row level security;

create table "public"."patient_photos" (
  "id"          uuid                     not null default gen_random_uuid(),
  "patient_id"  uuid                     not null,
  "uploaded_by" uuid                     not null,
  "angle"       text                     not null,
  "filename"    text                     not null default 'photo.jpg'::text,
  "file_url"    text                     not null,
  "file_key"    text                     not null default ''::text,
  "byte_size"   integer                  not null default 0,
  "created_at"  timestamp with time zone not null default now(),
  constraint "patient_photos_angle_check" check ((angle = ANY (ARRAY['frontal'::text, 'left'::text, 'right'::text, 'other'::text]))),
  constraint "patient_photos_pkey" primary key (id)
);

alter table "public"."patient_photos"
  enable row level security;

create table "public"."patient_scans" (
  "id"          uuid                     not null default gen_random_uuid(),
  "patient_id"  uuid                     not null,
  "uploaded_by" uuid                     not null,
  "file_key"    text                     not null,
  "file_url"    text                     not null,
  "file_name"   text                     not null default ''::text,
  "format"      text                     not null default ''::text,
  "created_at"  timestamp with time zone not null default now(),
  constraint "patient_scans_pkey" primary key (id)
);

alter table "public"."patient_scans"
  enable row level security;

create table "public"."patients" (
  "id"               uuid                     not null default gen_random_uuid(),
  "created_by"       uuid                     not null,
  "first_name"       text                     not null,
  "last_name"        text                     not null,
  "date_of_birth"    date                     not null,
  "address"          text                     not null default ''::text,
  "phone"            text                     not null default ''::text,
  "health_insurance" text                     not null default ''::text,
  "deleted"          boolean                  not null default false,
  "deleted_at"       timestamp with time zone,
  "created_at"       timestamp with time zone not null default now(),
  "updated_at"       timestamp with time zone not null default now(),
  "email"            text                     not null,
  "status"           text                     not null default 'pending'::text,
  constraint "patients_pkey" primary key (id),
  constraint "patients_status_check" check ((status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'in_review'::text, 'completed'::text, 'rejected'::text])))
);

alter table "public"."patients"
  enable row level security;

create table "public"."profiles" (
  "id"          uuid                     not null,
  "updated_at"  timestamp with time zone default now(),
  "name"        text,
  "email"       text,
  "phone"       text,
  "role"        text,
  "clinic_name" text,
  "verified"    boolean                  not null default false,
  "deleted"     boolean                  not null default false,
  constraint "profiles_pkey" primary key (id)
);

alter table "public"."profiles"
  enable row level security;

create table "public"."shade_detections" (
  "id"          uuid                     not null default gen_random_uuid(),
  "patient_id"  uuid                     not null,
  "uploaded_by" uuid                     not null,
  "file_key"    text                     not null,
  "file_url"    text                     not null,
  "file_name"   text                     not null default ''::text,
  "created_at"  timestamp with time zone not null default now(),
  constraint "shade_detections_pkey" primary key (id)
);

alter table "public"."shade_detections"
  enable row level security;

create table "public"."smile_previews" (
  "id"          uuid                     not null default gen_random_uuid(),
  "patient_id"  uuid                     not null,
  "uploaded_by" uuid                     not null,
  "file_key"    text                     not null,
  "file_url"    text                     not null,
  "file_name"   text                     not null default ''::text,
  "created_at"  timestamp with time zone not null default now(),
  constraint "smile_previews_pkey" primary key (id)
);

alter table "public"."smile_previews"
  enable row level security;

create or replace function public.handle_user_login_or_signup()
  returns trigger
  language plpgsql
  security definer
  AS $function$
BEGIN
  INSERT INTO public.profiles (
    id, 
    email, 
    name, 
    phone, 
    role, 
    clinic_name, 
    updated_at
  )
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'phone',
    COALESCE(new.raw_user_meta_data->>'role', 'clinic'),
    new.raw_user_meta_data->>'clinic_name',
    NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    -- Sync email if they update it in Auth, but preserve all custom profile fields (role, etc.)
    email = EXCLUDED.email,
    updated_at = NOW();

  RETURN new;
END;
$function$;

create or replace function public.has_patient_access (
  p_patient_id uuid,
  p_user_id    uuid
)
  returns boolean
  language sql
  security definer
  AS $function$
  select exists (
    select 1 from public.patients
    where id = p_patient_id 
      and created_by = p_user_id 
      and deleted = false
  ) or exists (
    select 1 from public.patient_access pa
    join public.patients p on p.id = pa.patient_id
    where pa.patient_id = p_patient_id 
      and pa.user_id = p_user_id 
      and p.deleted = false
  );
$function$;

create or replace function public.set_updated_at()
  returns trigger
  language plpgsql
  AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

create or replace function public.update_updated_at_column()
  returns trigger
  language plpgsql
  AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

alter table "public"."messages"
  add constraint "messages_conversation_id_fkey" foreign key (conversation_id) references public.conversations(id) on delete cascade;

alter table "public"."messages"
  add constraint "messages_reply_to_message_id_fkey" foreign key (reply_to_message_id) references public.messages(id) on delete set null;

alter table "public"."appointments"
  add constraint "appointments_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete cascade;

alter table "public"."notifications"
  add constraint "notifications_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete set null;

alter table "public"."patient_access"
  add constraint "patient_access_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete cascade;

alter table "public"."patient_audit_logs"
  add constraint "patient_audit_logs_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete set null;

alter table "public"."patient_notes"
  add constraint "patient_notes_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete cascade;

alter table "public"."patient_photos"
  add constraint "patient_photos_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete cascade;

alter table "public"."patient_scans"
  add constraint "patient_scans_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete cascade;

alter table "public"."profiles"
  add constraint "profiles_id_fkey" foreign key (id) references auth.users(id) on delete cascade;

alter table "public"."appointments"
  add constraint "appointments_created_by_fkey" foreign key (created_by) references public.profiles(id) on delete restrict;

alter table "public"."conversations"
  add constraint "conversations_user_a_fkey" foreign key (user_a) references public.profiles(id) on delete cascade;

alter table "public"."conversations"
  add constraint "conversations_user_b_fkey" foreign key (user_b) references public.profiles(id) on delete cascade;

alter table "public"."messages"
  add constraint "messages_sender_id_fkey" foreign key (sender_id) references public.profiles(id) on delete set null;

alter table "public"."notifications"
  add constraint "notifications_user_id_fkey" foreign key (user_id) references public.profiles(id) on delete cascade;

alter table "public"."patient_access"
  add constraint "patient_access_approved_by_fkey" foreign key (approved_by) references public.profiles(id) on delete set null;

alter table "public"."patient_access"
  add constraint "patient_access_granted_by_fkey" foreign key (granted_by) references public.profiles(id) on delete restrict;

alter table "public"."patient_access"
  add constraint "patient_access_requested_by_fkey" foreign key (requested_by) references public.profiles(id) on delete cascade;

alter table "public"."patient_access"
  add constraint "patient_access_user_id_fkey" foreign key (user_id) references public.profiles(id) on delete cascade;

alter table "public"."patient_audit_logs"
  add constraint "patient_audit_logs_actor_id_fkey" foreign key (actor_id) references public.profiles(id) on delete restrict;

alter table "public"."patient_notes"
  add constraint "patient_notes_author_id_fkey" foreign key (author_id) references public.profiles(id) on delete restrict;

alter table "public"."patient_photos"
  add constraint "patient_photos_uploaded_by_fkey" foreign key (uploaded_by) references public.profiles(id) on delete restrict;

alter table "public"."patient_scans"
  add constraint "patient_scans_uploaded_by_fkey" foreign key (uploaded_by) references public.profiles(id) on delete restrict;

alter table "public"."patients"
  add constraint "patients_created_by_fkey" foreign key (created_by) references public.profiles(id) on delete restrict;

alter table "public"."shade_detections"
  add constraint "shade_detections_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete cascade;

alter table "public"."shade_detections"
  add constraint "shade_detections_uploaded_by_fkey" foreign key (uploaded_by) references public.profiles(id) on delete restrict;

alter table "public"."smile_previews"
  add constraint "smile_previews_patient_id_fkey" foreign key (patient_id) references public.patients(id) on delete cascade;

alter table "public"."smile_previews"
  add constraint "smile_previews_uploaded_by_fkey" foreign key (uploaded_by) references public.profiles(id) on delete restrict;

create index idx_appointments_creator on public.appointments using btree (created_by, start_time desc);

create index idx_appointments_patient on public.appointments using btree (patient_id, start_time desc);

create index idx_appointments_time_range on public.appointments using btree (start_time, end_time);

create index idx_conversations_user_a on public.conversations using btree (user_a, updated_at desc);

create index idx_conversations_user_b on public.conversations using btree (user_b, updated_at desc);

create index idx_messages_conversation on public.messages using btree (conversation_id, created_at desc);

create index idx_messages_unread on public.messages using btree (conversation_id, sender_id)
  where (read_at is null);

create index idx_notifications_user_created on public.notifications using btree (user_id, created_at desc);

create index idx_notifications_user_unread on public.notifications using btree (user_id)
  where (read = false);

create index idx_patient_access_patient on public.patient_access using btree (patient_id);

create index idx_patient_access_status on public.patient_access using btree (patient_id, status);

create index idx_patient_access_user on public.patient_access using btree (user_id);

create index idx_patient_audit_actor on public.patient_audit_logs using btree (actor_id, created_at desc);

create index idx_patient_audit_patient on public.patient_audit_logs using btree (patient_id, created_at desc);

create index idx_patient_notes_patient on public.patient_notes using btree (patient_id, created_at desc);

create index idx_patient_photos_patient on public.patient_photos using btree (patient_id, created_at desc);

create index idx_patient_scans_patient on public.patient_scans using btree (patient_id, created_at desc);

create index idx_patients_created_by on public.patients using btree (created_by)
  where (deleted = false);

create index idx_patients_name on public.patients using btree (last_name, first_name);

create index idx_patients_status on public.patients using btree (status)
  where (deleted = false);

create index idx_shade_detections_patient on public.shade_detections using btree (patient_id, created_at desc);

create index idx_smile_previews_patient on public.smile_previews using btree (patient_id, created_at desc);

create trigger on_auth_user_created_or_updated
  after insert or update on auth.users
  for each row
  execute function public.handle_user_login_or_signup();

create trigger update_appointments_updated_at
  before update on public.appointments
  for each row
  execute function public.update_updated_at_column();

create trigger trg_patient_notes_updated_at
  before update on public.patient_notes
  for each row
  execute function public.set_updated_at();

create trigger trg_patients_updated_at
  before update on public.patients
  for each row
  execute function public.set_updated_at();

create policy "appointments_delete_authenticated" on "public"."appointments"
  for delete
  to "authenticated"
  using (true);

create policy "appointments_insert_authenticated" on "public"."appointments"
  for insert
  to "authenticated"
  with check (true);

create policy "appointments_select_own_or_shared" on "public"."appointments"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.patients p
  where ((p.id = appointments.patient_id) AND (p.deleted = false) AND ((p.created_by = auth.uid()) or (exists ( select 1
           from public.patient_access a
          where ((a.patient_id = p.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text)))))))));

create policy "appointments_update_authenticated" on "public"."appointments"
  for update
  to "authenticated"
  using (true)
  with check (true);

create policy "Users can view their own conversations" on "public"."conversations"
  for select
  to "authenticated"
  using (((auth.uid() = user_a) or (auth.uid() = user_b)));

create policy "Users can view messages in their conversations" on "public"."messages"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.conversations c
  where ((c.id = messages.conversation_id) AND ((c.user_a = auth.uid()) or (c.user_b = auth.uid()))))));

create policy "notifications_select_own" on "public"."notifications"
  for select
  to "authenticated"
  using ((user_id = auth.uid()));

create policy "notifications_update_own" on "public"."notifications"
  for update
  to "authenticated"
  using ((user_id = auth.uid()))
  with check ((user_id = auth.uid()));

create policy "patient_access_manage_owner" on "public"."patient_access"
  for all
  to "authenticated"
  using ((exists ( select 1
   from public.patients p
  where ((p.id = patient_access.patient_id) AND (p.created_by = auth.uid())))));

create policy "patient_access_request_shared" on "public"."patient_access"
  for insert
  to "authenticated"
  with check (((requested_by = auth.uid()) AND (status = 'pending'::text) AND (EXISTS ( SELECT 1
   FROM public.patient_access a
  WHERE ((a.patient_id = a.patient_id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text))))));

create policy "patient_access_select" on "public"."patient_access"
  for select
  to "authenticated"
  using (((user_id = auth.uid()) or (requested_by = auth.uid()) or (granted_by = auth.uid()) or (exists ( select 1
   from public.patients p
  where ((p.id = patient_access.patient_id) AND (p.created_by = auth.uid()))))));

create policy "patient_audit_logs_insert" on "public"."patient_audit_logs"
  for insert
  to "authenticated"
  with check ((actor_id = auth.uid()));

create policy "patient_audit_logs_select" on "public"."patient_audit_logs"
  for select
  to "authenticated"
  using (((actor_id = auth.uid()) or (exists ( select 1
   from public.patients p
  where ((p.id = patient_audit_logs.patient_id) AND (p.created_by = auth.uid()))))));

create policy "patient_notes_insert" on "public"."patient_notes"
  for insert
  to "authenticated"
  with check (((author_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.patients p
  WHERE ((p.id = patient_notes.patient_id) AND ((p.created_by = auth.uid()) OR (EXISTS ( SELECT 1
           FROM public.patient_access a
          WHERE ((a.patient_id = p.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text))))))))));

create policy "patient_notes_modify" on "public"."patient_notes"
  for all
  to "authenticated"
  using (((author_id = auth.uid()) or (exists ( select 1
   from public.patients p
  where ((p.id = patient_notes.patient_id) AND (p.created_by = auth.uid()))))));

create policy "patient_notes_select" on "public"."patient_notes"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.patients p
  where ((p.id = patient_notes.patient_id) AND ((p.created_by = auth.uid()) or (exists ( select 1
           from public.patient_access a
          where ((a.patient_id = p.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text)))))))));

create policy "patient_photos_select_own_or_shared" on "public"."patient_photos"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.patients p
  where ((p.id = patient_photos.patient_id) AND (p.deleted = false) AND ((p.created_by = auth.uid()) or (exists ( select 1
           from public.patient_access a
          where ((a.patient_id = p.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text)))))))));

create policy "patient_scans_select_own_or_shared" on "public"."patient_scans"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.patients p
  where ((p.id = patient_scans.patient_id) AND (p.deleted = false) AND ((p.created_by = auth.uid()) or (exists ( select 1
           from public.patient_access a
          where ((a.patient_id = p.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text)))))))));

create policy "patients_delete_owner" on "public"."patients"
  for delete
  to "authenticated"
  using ((created_by = auth.uid()));

create policy "patients_insert_authenticated" on "public"."patients"
  for insert
  to "authenticated"
  with check ((created_by = auth.uid()));

create policy "patients_select_own_or_shared" on "public"."patients"
  for select
  to "authenticated"
  using (((created_by = auth.uid()) or (exists ( select 1
   from public.patient_access a
  where ((a.patient_id = patients.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text))))));

create policy "patients_update_owner" on "public"."patients"
  for update
  to "authenticated"
  using ((created_by = auth.uid()))
  with check ((created_by = auth.uid()));

create policy "Users can update own profile" on "public"."profiles"
  for update
  to PUBLIC
  using ((auth.uid() = id));

create policy "Users can view own profile" on "public"."profiles"
  for select
  to PUBLIC
  using ((auth.uid() = id));

create policy "shade_detections_select_own_or_shared" on "public"."shade_detections"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.patients p
  where ((p.id = shade_detections.patient_id) AND (p.deleted = false) AND ((p.created_by = auth.uid()) or (exists ( select 1
           from public.patient_access a
          where ((a.patient_id = p.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text)))))))));

create policy "smile_previews_select_own_or_shared" on "public"."smile_previews"
  for select
  to "authenticated"
  using ((exists ( select 1
   from public.patients p
  where ((p.id = smile_previews.patient_id) AND (p.deleted = false) AND ((p.created_by = auth.uid()) or (exists ( select 1
           from public.patient_access a
          where ((a.patient_id = p.id) AND (a.user_id = auth.uid()) AND (a.status = 'approved'::text)))))))));

comment on column "public"."messages"."mentioned_patients" is 'Array of {id, label} patient @mentions referenced in content';

grant execute on function "public"."handle_user_login_or_signup"() to public, "anon", "authenticated", "postgres", "service_role";

grant execute on function "public"."has_patient_access"(uuid, uuid) to public, "anon", "authenticated", "postgres", "service_role";

grant execute on function "public"."set_updated_at"() to public, "anon", "authenticated", "postgres", "service_role";

grant execute on function "public"."update_updated_at_column"() to public, "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."Notifications" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."appointments" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."conversations" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."messages" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."notifications" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."patient_access" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."patient_audit_logs" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."patient_notes" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."patient_photos" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."patient_scans" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."patients" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."profiles" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."shade_detections" to "anon", "authenticated", "postgres", "service_role";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."smile_previews" to "anon", "authenticated", "postgres", "service_role";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "anon";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "service_role";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "anon";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "authenticated";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "service_role";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "anon";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "authenticated";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "service_role";

